# Generated by Django 4.2.7 on 2023-12-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='image',
            field=models.URLField(blank=True, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='opisanie',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
