# Generated by Django 4.2.7 on 2023-12-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_actor_image_director_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Трейлер'),
        ),
    ]
