# Generated by Django 4.2.7 on 2023-12-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_profileuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='balance',
            field=models.IntegerField(default=10),
        ),
    ]
